# coding: utf-8

# flake8: noqa
"""
    App API

    Development documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from api_client.models.auth_response import AuthResponse
from api_client.models.auth_response_user import AuthResponseUser
from api_client.models.error_response import ErrorResponse
from api_client.models.get_user_me200_response import GetUserMe200Response
from api_client.models.get_user_me401_response import GetUserMe401Response
from api_client.models.patch_user_name_request import PatchUserNameRequest
from api_client.models.post_auth_login_request import PostAuthLoginRequest
from api_client.models.post_auth_register_request import PostAuthRegisterRequest
from api_client.models.post_exist200_response import PostExist200Response
from api_client.models.post_exist_request import PostExistRequest
from api_client.models.user import User
