# coding: utf-8

# flake8: noqa

"""
    App API

    Development documentation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AuthResponse",
    "AuthResponseUser",
    "ErrorResponse",
    "GetUserMe200Response",
    "GetUserMe401Response",
    "PatchUserNameRequest",
    "PostAuthLoginRequest",
    "PostAuthRegisterRequest",
    "PostExist200Response",
    "PostExistRequest",
    "User",
]

# import apis into sdk package
from api_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from api_client.api_response import ApiResponse as ApiResponse
from api_client.api_client import ApiClient as ApiClient
from api_client.configuration import Configuration as Configuration
from api_client.exceptions import OpenApiException as OpenApiException
from api_client.exceptions import ApiTypeError as ApiTypeError
from api_client.exceptions import ApiValueError as ApiValueError
from api_client.exceptions import ApiKeyError as ApiKeyError
from api_client.exceptions import ApiAttributeError as ApiAttributeError
from api_client.exceptions import ApiException as ApiException

# import models into sdk package
from api_client.models.auth_response import AuthResponse as AuthResponse
from api_client.models.auth_response_user import AuthResponseUser as AuthResponseUser
from api_client.models.error_response import ErrorResponse as ErrorResponse
from api_client.models.get_user_me200_response import GetUserMe200Response as GetUserMe200Response
from api_client.models.get_user_me401_response import GetUserMe401Response as GetUserMe401Response
from api_client.models.patch_user_name_request import PatchUserNameRequest as PatchUserNameRequest
from api_client.models.post_auth_login_request import PostAuthLoginRequest as PostAuthLoginRequest
from api_client.models.post_auth_register_request import PostAuthRegisterRequest as PostAuthRegisterRequest
from api_client.models.post_exist200_response import PostExist200Response as PostExist200Response
from api_client.models.post_exist_request import PostExistRequest as PostExistRequest
from api_client.models.user import User as User
